### ISSUE TITLE
"Import Profile" ignores LulzBot profile Identifier and Name (and probably Description)

### ISSUE THREAD

**Issue by b-morgan** [Garr-R/OctoPrint-Slicer#3]
I have a LulzBot TAZ 6 printer configured in PrusaSlicer and executed an Export, Config, and saved the file as config.ini (included in .zip below). 

I then clicked `Import Profile...`, browsed to the file on my desktop, and entered an Identifier and Name (I left the Description blank). After clicking `Confirm` the imported config was identified as config and named config. I believe that the Identifier and Name should have come from the `Import Profile...` values.

![image](https://github.com/Garr-Garr/OctoPrint-InternalSlicer/assets/1547854/a934891b-7ed2-480f-96f3-3bdaeedc47fa)

[config.zip](https://github.com/Garr-Garr/OctoPrint-InternalSlicer/files/14670902/config.zip)

     OctoPrint 1.10.0rc3 Python 3.9.2 OctoPi* 1.0.0cam (build 2023.07.20.144556)

**Comment by b-morgan** [comment]
This install is on an RPi 4B which does not normally have my printer attached. The printer is normally attached to an RPi 3B running OctoPi 0.18.0 and OctoPrint 1.10.0rc3.

**Comment by Garr-Garr** [comment]
@b-morgan I'm fairly certain this issue is now fixed in the latest update! I haven't made a new release yet, but you can test it out by downloading the .zip file and uploading it to OctoPrint via the Plugin Manager:

![image](https://github.com/user-attachments/assets/f385f8c4-8ce8-4154-8965-55a4e2b5f5d3)
